"""DataUnderstanding model for storing EDA results."""

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import ForeignKey, Index
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.dataset import Dataset


class DataUnderstanding(BaseModel):
    """
    DataUnderstanding model for storing exploratory data analysis results.

    Stores summary statistics, column information, quality issues,
    and preprocessing recommendations generated by the EDA agent.
    """

    __tablename__ = "data_understandings"

    # Foreign key to dataset
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("datasets.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    # Summary statistics (JSONB)
    summary_stats: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
        comment="row_count, column_count, missing_percent, duplicate_rows",
    )

    # Column information (JSONB array)
    columns: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="Column details: name, dtype, missing_percent, unique_count, distribution_summary",
    )

    # Data quality issues (JSONB array)
    quality_issues: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="Quality issues: type, severity, description, affected_columns",
    )

    # User-facing data quality warnings (JSONB array)
    quality_warnings: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment=(
            "Validation warnings: level, message, metric, value, threshold, affected_columns"
        ),
    )

    # Preprocessing recommendations
    recommended_preprocessing: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        default=list,
        nullable=False,
        comment="Recommended preprocessing steps",
    )

    # Causal analysis hints (from EDA agent)
    treatment_candidates: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        default=list,
        nullable=False,
        comment="Potential treatment variables identified by EDA",
    )
    outcome_candidates: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        default=list,
        nullable=False,
        comment="Potential outcome variables identified by EDA",
    )
    confounder_candidates: Mapped[list[str]] = mapped_column(
        ARRAY(String),
        default=list,
        nullable=False,
        comment="Potential confounders identified by EDA",
    )

    # Preprocessing metadata
    preprocessing_applied: Mapped[bool] = mapped_column(
        default=False,
        nullable=False,
        comment="Whether preprocessing was performed",
    )
    preprocessing_steps: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="Serialized PreprocessingStep objects with step_type, affected_columns, parameters, statistics",
    )
    preprocessed_row_count: Mapped[int | None] = mapped_column(
        nullable=True,
        comment="Row count after preprocessing (may differ due to outlier removal)",
    )
    preprocessed_column_count: Mapped[int | None] = mapped_column(
        nullable=True,
        comment="Column count after preprocessing (may increase with one-hot encoding)",
    )
    preprocessing_config: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
        comment="Configuration used for preprocessing",
    )

    # Relationships
    dataset: Mapped["Dataset"] = relationship(
        "Dataset",
        back_populates="data_understanding",
    )

    # Indexes for common query patterns
    __table_args__ = (
        Index("ix_data_understandings_dataset_id", "dataset_id"),
    )
